project_base_dir: ./
result_base_dir: ./data_process_pipeline/tiktok_results

# culture relevance classifier
0_culture_relevance_classifier:
  input_file: data_process_pipeline/tiktok_data/tiktok_subset.csv
  output_file: data_process_pipeline/tiktok_results/0_culture_relevance_classifier/output.csv
  classifier_path: SALT-NLP/CultureBank-Relevance-Classifier
  model_name: distilbert-base-uncased
  device: cuda:0
  field_name_with_comments: comment_content
  batch_size: 512
  field_name_with_submission_title: eval_scenario
  field_name_with_vid: topic
  field_name_with_submission_text: eval_whole_desc

# llm-based knowledge extractor
1_knowledge_extractor:
  input_file: data_process_pipeline/tiktok_results/0_culture_relevance_classifier/output.csv
  output_raw: data_process_pipeline/tiktok_results/1_knowledge_extractor/output_raw.csv
  output_file: data_process_pipeline/tiktok_results/1_knowledge_extractor/output.csv
  pattern: plain
  model: mistralai/Mistral-7B-Instruct-v0.2
  num_samples: -1
  partition: -1
  sanity_check: False

# convert negation
2_negation_converter:
  input_file: data_process_pipeline/tiktok_results/1_knowledge_extractor/output.csv
  output_file: data_process_pipeline/tiktok_results/2_negation_converter/output.csv

# clustering component
3_clustering_component:
  input_file: data_process_pipeline/tiktok_results/1_knowledge_extractor/output.csv
  output_file: data_process_pipeline/tiktok_results/3_clustering_component/output.csv
  output_score_file: data_process_pipeline/tiktok_results/3_clustering_component/score.json
  output_filtered_file: data_process_pipeline/tiktok_results/3_clustering_component/output_filtered.csv
  cultural_group_threshold: 0.3
  sent_threshold: 0.4
  min_cluster_size: 1
  with_other_desc: true
  annotated_file: none
  sbert:
    model: all-MiniLM-L6-v2

# cluster summarizer
4_cluster_summarizer:
  input_file: data_process_pipeline/tiktok_results/3_clustering_component/group=0.3_sent=0.4_otherdesc=False/output_filtered.csv
  output_file: data_process_pipeline/tiktok_results/4_cluster_summarizer/output.csv
  original_before_cluster_file: data_process_pipeline/tiktok_results/1_knowledge_extractor/output.csv
  pattern: plain
  model: mistralai/Mistral-7B-Instruct-v0.2
  num_samples: -1
  partition: -1
  sanity_check: False
  filter_threshold: -1

# topic normalization
5_topic_normalizer:
  input_file: data_process_pipeline/tiktok_results/4_cluster_summarizer/output.csv
  output_file: data_process_pipeline/tiktok_results/5_topic_normalizer/output.csv
  output_score_file: data_process_pipeline/tiktok_results/5_topic_normalizer/output_score.json
  cultural_group_threshold: 0.3
  sbert:
    model: all-MiniLM-L6-v2
  openai:
    model: gpt-3.5-turbo-1106
    temperature: 0.5
    max_tokens: 20
    top_p: 0.3
    seed: 1234

# agreement calculator
6_agreement_calculator:
  input_file: data_process_pipeline/tiktok_results/5_topic_normalizer/group=0.3/output.csv
  output_file: data_process_pipeline/tiktok_results/6_agreement_calculator/output.csv

# content moderation
7_content_moderation:
  input_file: data_process_pipeline/tiktok_results/6_agreement_calculator/output.csv
  output_file: data_process_pipeline/tiktok_results/7_content_moderation/output.csv
  output_file_for_manual_annotation: data_process_pipeline/tiktok_results/7_content_moderation/output_for_annotation.csv
  hard_api_threshold: 0.2
  soft_api_threshold: 0.1
  keyword_list_dir: data_process_pipeline/dummy_data/list_of_words.txt
  device: cuda:0
  controversial_field_name_to_annotate: controversial_or_PII
  model_dir: SALT-NLP/CultureBank-Controversial-Classifier

8_final_formatter:
  input_file: data_process_pipeline/tiktok_results/7_content_moderation/output.csv
  output_file: data_process_pipeline/tiktok_results/8_final_formatter/output.csv
  controversial_annotation_file: data_process_pipeline/tiktok_results/7_content_moderation/human_annotation.csv
